import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { AppProvider } from '@/contexts/AppContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}>
        {/* ブラー背景画像 */}
        <div
          className="fixed inset-0 bg-cover bg-center bg-no-repeat bg-fixed blur-[3px] -z-20"
          style={{
            backgroundImage: "url('./img/bg.jpg')",
          }}
        />

        {/* 半透明オーバーレイ */}
        <div className="fixed inset-0 bg-white/50 -z-10" />

        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
